config/routes.rb
Rails.application.routes.draw do
  
  root 'products#index'

  devise_for :users, controllers: {registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks"}


  devise_scope :user do
    get 'signout', to: 'devise/sessions#destroy', as: :signout
  end
  
  resources :products do 
    resources :product_images
  end

  # resources :posts do
  #   resources :comments
  # end
  
  resources :seller_profiles
  # resources :password_resets

  get "/orders", to: 'orders#new'
  get "/orders/:id", to: 'orders#show'
  post "orders/:id", to: 'orders#create'
  patch "orders/:id", to: 'orders#update'

  get "/carted_products", to: 'carted_products#index'
  get "carted_products/:id", to: 'carted_products#show'
  post "/carted_products", to: 'carted_products#create'
  delete "/carted_products/:id", to: 'carted_products#destroy'


  post "/searches", to: 'searches#index'

  get '/searches', to: 'searches#index'

  get "/about", to: 'pages#about'
  get "/contact", to: 'pages#contact'
  get "/challenge", to: 'pages#challenge'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carted_product.rb
class CartedProduct < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :user, optional: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :products, through: :category_products
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :product, optional: true
  belongs_to :category, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :carted_products
  has_many :products, through: :carted_products
  belongs_to :user, optional: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, through: :carted_products
  has_many :carted_products, dependent: :destroy
  belongs_to :user , optional: true

  has_many :product_images, dependent: :destroy

  has_many :category_products
  has_many :categories, through: :category_products

  validates :price, numericality: {greater_than: 0}
  validates :name, presence: true 
  validates :description, presence: true

  belongs_to :seller_profile, optional: true

  def tax
    price * 0.09
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product

  mount_uploader :image_url, ProductImageUploader
end

app/models/seller_profile.rb
class SellerProfile < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :company_name, presence: true
  validates :company_email, presence: true
  validates :street_code, presence: true
  validates :location, presence: true
  validates :contact, presence: true


  mount_uploader :seller_logo, ProductImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]
  has_many :orders
  has_many :posts
  has_one :seller_profile
  has_many :products, through: :seller_profile
  has_many :products, through: :carted_products

  # before_create { generate_token(:auth_token)}

  # def send_password_reset
  #   generate_token(:password_reset_token)
  #   self.password_reset_sent_at = Time.zone.now
  #   save!
  #   UsermailerMailer.password_reset(self).deliver_now
  # end

  # def generate_token(column)
  #   begin
  #     self[column] = SecureRandom.urlsafe_base64
  #   end while User.exists?(column => self[column])
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MadeInRwanda</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Barrio|Josefin+Sans|Sansita" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <link  href="https://fonts.googleapis.com/css?family=Chewy|
    Permanent+Marker" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link  href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'ckeditor/ckeditor' %>


    
  </head>
 <body>
<!-- begin navbar -->
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img class="animated infinite rubberBand"></a>
      <a class="navbar-brand" href="/">MadeinRwanda<span></span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">HOME<span class="sr-only">(current)</span></a></li>
          
          <ul class="nav navbar-nav navbar-right">
  
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Filter Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/products?sort=asc">Price (Low to High)</a></li>
            <li><a href="/products?sort=desc">Price (High to Low)</a></li>
           <!--  <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li> -->
          </ul>
        </li>
      </ul>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
          
          <ul class="dropdown-menu">
            <% Category.joins(:products).distinct.each do |category| %>
              <li> <a href="#" ><%= link_to category.name, products_path(category: category.name)%></a></li>
            <% end %>
          </ul>
        </li>
      </ul>

       <%= form_tag "/searches", class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="search_input">
        <button style="background-color: #"><a class="btn-floating btn-small" role="button" ><i class="fa fa-search" align="center"></i></a></button>
        <% end %>
        </div>

      <!-- <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="search_query">
        </div>
       <button><a class="btn-floating btn-small blue"><i class="fa fa-search"></i></a></button>
      </form> -->
       <ul class="nav navbar-nav navbar-right">
       <!-- 

          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul> -->
         <% if user_signed_in? %>
              <li><a href="<%= signout_path %>" class=" nav-content-format" role="button" ><strong>Sign Out</strong></a></li>
               <li><a class="glyphicon glyphicon-shopping-cart" href="/carted_products">Cart<sup class="shopping_cart"><%= shopping_cart %></sup></a></li>
            <% else %>
              <li><%= link_to "Sign In", "/users/sign_in" %></li>
              <li><a class="glyphicon glyphicon-shopping-cart" href="/carted_products">Cart<sup class="shopping_cart"><%= shopping_cart %></sup></a></li>
            <% end %>
        </li>
      </ul>

    

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



    <!-- <input type="checkbox" id="menuToggle"> 
    <label for="menuToggle" class="menu-icon">&#9776;</label>

<header>
  <div id="brand">Let's Enjoy What We Make</div>
  <style type="text/css">
            * { padding: 0; margin: 0; }
            body {
              font-family: sans-serif;
            }

            a {
              text-decoration: none;
              color:#00A5CC;
            }
            
            li {
              list-style-type: none;
            }

            header {
              width: 100%;
              height: 50px;
              margin: auto;
              border-bottom: 1px solid #EEE;
            }

            #brand {
              float: left;
              line-height: 50px;
              color: #E5DAC0;
              font-size: 25px;
              font-weight: bolder;
            }

            nav {
              width: 100%;
              text-align: center;
            }

            .menu a {
              display: block; 
              padding: 15px 0; 
              border-bottom: 1px solid #B49755;
              color: #F0EADC;
              text-decoration: none;
            }

            .menu li:last-child a {
              border-bottom: none;
            }

            .menu a:hover {
              background: #E5DAC0;
              color: #FFF;
            }

            .menu {
              width: 240px;
              height: 100%;
              z-index: 1;
              position: absolute;
              background: #D9C9A3;
              left: -240px;
              transition: all .3s ease-in-out;
              -webkit-transition: all .3s ease-in-out;
              -moz-transition: all .3s ease-in-out;
              -ms-transition: all .3s ease-in-out;
              -o-transition: all .3s ease-in-out;

            }

            .menu-icon {
              padding: 10px 20px;
              background: #E5DAC0;
              color: #987D3E;
              cursor: pointer;
              float: left;
              margin-top: 4px;
              border-radius: 5px;
            }
            #menuToggle {
              display: none;

            }

            #menuToggle:checked ~ .menu {
              position: absolute;
              left: 0;
            }

  </style> 
</header>

  <nav class="menu">
    <ul>
      <li><a href="#">HOME</a></li>
      <li><a href="#">ABOUT</a></li>
      <li><a href="#">WORK</a></li>
      <li><a href="#">INSPIRATION</a></li>
      <li><a href="#">BLOG</a></li>
      <li><a href="#">CONTACT</a></li>

    </ul>
  </nav> -->

<!--         <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script> 
        $(function(){
            $('#test').popover();​
        });
         </script>



 -->

 <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : ENV['FACEBOOK_KEY'],
      xfbml      : true,
      version    : 'v2.10'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
  <body>
             <p>
          <% flash.each do |key, value| %>
          <% alert_class = case key
          when :notice then "success"
          when :alert then "danger"
          else key
           end %>
           <%= content_tag :div, class: "alert alert-#{alert_class}" do %>
           <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <%= value %>
           <% end %>
           <% end %>
         </p>
    <%= yield %>

    <footer>
      <div class="site-footer">
        <div class="container">
            <div class="row">
              <div class="col-md-5">
              <p style="float: right; font-size: 18px; color:  #99ff99;">Enjoy What You Make</p>
              <h4 style="color:  #99ff99;">Contact Address</h4>
                <address>
                  Kigali Rwanda, <br>
                  Made in Rwanda Products,<br>
                  (+250)725085564
                </address>
              </div>
              </div>

            <div class="bottom-footer">
              <div class="col-md-5">© Copyright MadeinRwanda <%= Time.now.year %></div>
            <div class="col-md-7">
                  <ul class="footer-nav">
                      <li><a href="/">Home</a></li>
                      <% if current_user && current_user.seller_profile%>
                      <li><a href="/seller_profiles/<%= current_user.seller_profile.id %>">Your store</a></li>
                      <% elsif current_user && !current_user.seller_profile %>
                      <li><a href="/seller_profiles/new?user_id=<%= current_user.id %>">Sell With Us</a></li> 
                      <% end %>                  
                      <li><a href="#">Category</a></li>
                      <li><a href="/contact">Contact</a></li>
                      <li><a href="/about">About Us</a></li>
                  </ul>
              </div>
            </div>
      </div>
    </footer>
  </body>
</html>